global:
  scrape_interval: 15s

scrape_configs:
  - job_name: backend
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: recommendation
    metrics_path: /metrics
    static_configs:
      - targets: ["recommendation:8000"]
